### ISSUE TITLE
[问]Is there a support ARM64 plan？

### ISSUE THREAD

**Issue by GeekWorkCode** [taigaio/taiga-docker#26]
But I have a good server is ARM64 architecture. So I want to use it to deploy the experience

**Comment by tdelatorre** [comment]
Hi! Sorry, but we haven't tested it on an ARM architecture. 
What kind of problems do you have? Maybe we can help you.
Greetings!

**Comment by WiZeYAR** [comment]
There was a person, proposing how to build the arm64 image here: https://github.com/taigaio/taiga-docker/issues/70#issuecomment-818781244

**Comment by Felixkruemel** [comment]
> 
> 
> Hi! Sorry, but we haven't tested it on an ARM architecture.
> What kind of problems do you have? Maybe we can help you.
> Greetings!

The Docker images are just not available for aarch64/ARM64. Simple as that.
You need to build the images Multi-Arch to comply with dockers Multi-Arch approach: https://docs.docker.com/desktop/multi-arch/

That there's no ARM support is an rising problem as powerful and cheap servers on ARM get more and more popular, especially since certain providers offer them for free. 

As @WiZeYAR mentioned above the comment explained well what needs to be changed.

**Comment by miku86** [comment]
Would be awesome to see this, more and more people use ARM infrastructure.

**Comment by mosgjig** [comment]
For those interested in deploying arm images via helm, from [taigaio/taiga-docker#70 (comment)](https://github.com/taigaio/taiga-docker/issues/70#issuecomment-818781244), to raspberry pi k8s cluster running on ubuntu with microk8s:

### Pre-requisits:
 - Install cert manager for letsencrypt - https://cert-manager.io/docs/installation/helm/

### Taiga Helm Resource:
 - https://github.com/nemonik/taiga-helm

 ### values.yaml
Use the following `values.yaml`, find and replace below values:
 - `<my.domain.com>`
 - `microk8s-hostpath` - this may be different for your environment.
 - `letsencrypt-staging` - this may be different for you environment.

```
persistence:
  media:
    enabled: true
    size: '100Mi'
    storageClassName: microk8s-hostpath
    accessMode: 'ReadWriteOnce'
  static:
    enabled: true
    size: '100Mi'
    storageClassName: microk8s-hostpath
    accessMode: 'ReadWriteOnce'

env:
  taigaURL: "https://<my.domain.com>"
  taigaWebsocketsURL: "wss://<my.domain.com>" ## wss:// if https
  taigaSitesDomain: "<my.domain.com>" 
  taigaSitesScheme: "https"
  postgresHost: "taiga-db"

taigaAsyncRabbitmq:
  persistence:
    enabled: true
    size: '100Mi'
    storageClassName: microk8s-hostpath
    accessMode: 'ReadWriteOnce'
  service:
    type: ClusterIP
    port: 5672

taigaAsync:
  service:
    type: ClusterIP
    port: 8000
  image:
    repository: public.ecr.aws/r2d7r3i9/taiga-back
    tag: latest

taigaBack:
  service:
    type: ClusterIP
    port: 8000
  image:
    repository: public.ecr.aws/r2d7r3i9/taiga-back
    tag: latest

taigaDB:
  image:
    repository: postgres
    tag: "12.3"
  persistence:
    enabled: true
    size: '100Mi'
    storageClassName: microk8s-hostpath
    accessMode: 'ReadWriteOnce'
  service:
    type: ClusterIP
    port: 5432

taigaEventsRabbitmq:
  persistence:
    enabled: true
    size: '100Mi'
    storageClassName: microk8s-hostpath
    accessMode: 'ReadWriteOnce'
  service:
    type: ClusterIP
    port: 5672

taigaEvents:
  service:
    type: ClusterIP
    port: 8888
  image:
    repository: public.ecr.aws/r2d7r3i9/taiga-events
    tag: latest

taigaFront:
  service:
    type: ClusterIP
    port: 80
  image:
    repository: public.ecr.aws/r2d7r3i9/taiga-front
    tag: latest

taigaGateway:
  image:
    repository: public.ecr.aws/r2d7r3i9/taiga-gateway
    tag: latest
  persistence:
    enabled: true
    size: '100Mi'
    storageClassName: microk8s-hostpath
    accessMode: 'ReadWriteOnce'
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "public"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    hosts:
      - host: <my.domain.com>
        paths:
          -  "/"
    tls:
      - secretName: taiga-tls
        hosts:
          - <my.domain.com>

taigaProtected:
  image:
    repository: public.ecr.aws/r2d7r3i9/taiga-protected
    tag: latest
  service:
    type: ClusterIP
    port: 8003

taigaAsyncRabbitmq:
  persistence:
    enabled: true
    storageClassName: microk8s-hostpath

```

### Conclusion
when all is said and done you have a standing app but can't login.  Supposedly default l/p is `admin/123123` but that doesn't work.  Looking at the docs, one will have to run a shell script via docker container to create the user.  If somebody can provide an easier answer, lmk.  For now ditching this and attempting OpenProject.
