### ISSUE TITLE
[Q] Problems in getting slack notifications to work

### ISSUE THREAD

**Issue by erueda1** [taigaio/taiga-docker#33]
Hello, I am having trouble getting slack notifications to work. First of all say that what I use is Rocket.chat, but I understand that it is 100% compatible. This is my scenario:
![Captura de pantalla de 2021-07-22 18-33-10](https://user-images.githubusercontent.com/53336366/126675348-06477b59-4c82-445b-b00b-567bb53a88a8.png)

I know that Slack is integrated by default at the docker images according to the[ 30 minutes guide](https://resources.taiga.io/30min-setup/#slack-settings), but the problem persists.

This is all the configuration that i am using:

- **docker-compose.yml**
```
version: "3.5"
x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - ./data/taiga-media-data:/taiga-back/media
  - ./settings/config.py:/taiga-back/settings/config.py
services:
  taiga-back:
    image: taigaio/taiga-back:latest
    volumes: *default-back-volumes
    environment:
      ENABLE_SLACK: "True"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq
    ports:
      - 8000:8000
  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-back
      - taiga-async-rabbitmq
  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: rabbit_password
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - ./data/taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga
  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: rabbit_password
      TAIGA_SECRET_KEY: "taiga_secret"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq
    ports:
      - 8888:8888
  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: rabbit_password
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - ./data/taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga
  taiga-front:
    image: taigaio/taiga-front
    environment:
      ENABLE_SLACK: "true"
    networks:
      - taiga
    volumes:
      - ./settings/conf.json:/usr/share/nginx/html/conf.json
    ports:
      - 8082:80
  taiga-protected:
    image: taigaio/taiga-protected:latest
    volumes: #*default-back-volumes    
      - ./data/taiga-media-data:/taiga-protected/media
    environment:
      MAX_AGE: 360
      SECRET_KEY: "taiga_secret"
    networks:
      - taiga
    ports:
      - 8003:8003
  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - ./data/taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
volumes:
  taiga-static-data:
networks:
  taiga:
```
**- nginx vhost** of taiga-gateway is exactly like [this](https://github.com/kaleidos-ventures/taiga-docker/blob/main/taiga-gateway/taiga.conf)
**- conf.json**
```
{
    "api": "https://projects.example.com/api/v1/",
    "eventsUrl": null,
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": false,
    "debugInfo": false,
    "defaultLanguage": "es",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "defaultLoginEnabled": true,
    "loginFormType": "ldap",
    "publicRegisterEnabled": false,
    "feedbackEnabled": false,
    "supportUrl": "https://www.example.com",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "tagManager": { "accountId": null },
    "tribeHost": null,
    "enableAsanaImporter": false,
    "enableGithubImporter": false,
    "enableJiraImporter": false,
    "enableTrelloImporter": false,
    "gravatar": false,
    "rtlLanguages": ["ar", "fa", "he"]
}
```

- **config.py**

```
# -*- coding: utf-8 -*-
import os
from .common import *   # noqa, pylint: disable=unused-wildcard-import
#########################################
## GENERIC
#########################################
DEBUG = False
#ADMINS = (
#    ("Admin", "example@example.com"),
#)
DATABASES = {
      ...my database config...
    }
}
SECRET_KEY = "taiga_secret"
TAIGA_URL = "https://projects.example.com"
SITES = {
    "api": {"domain": "projects.example.com", "scheme": "https", "name": "api"},
    "front": {"domain": "projects.example.com", "scheme": "https", "name": "front"}
}
# Setting DEFAULT_PROJECT_SLUG_PREFIX to false
# removes the username from project slug
DEFAULT_PROJECT_SLUG_PREFIX = False
#########################################
## MEDIA AND STATIC
#########################################
MEDIA_ROOT = '/taiga-back/media'
MEDIA_URL = f"{ TAIGA_URL }/media/"
DEFAULT_FILE_STORAGE = "taiga_contrib_protected.storage.ProtectedFileSystemStorage"
THUMBNAIL_DEFAULT_STORAGE = DEFAULT_FILE_STORAGE
STATIC_ROOT = '/static'
STATIC_URL = f"{ TAIGA_URL }/static/"
#########################################
## EMAIL
#########################################
.. my email config...
#########################################
## EVENTS
#########################################
EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {
    "url": "amqp://taiga:rabbit_password@taiga6_taiga-events-rabbitmq_1:5672/taiga"
}
#########################################
## TAIGA ASYNC
#########################################
CELERY_ENABLED = os.getenv('CELERY_ENABLED', 'True') == 'True'
from kombu import Queue  # noqa
CELERY_BROKER_URL = "amqp://taiga:rabbit_password@taiga6_taiga-events-rabbitmq_1:5672/taiga"
CELERY_RESULT_BACKEND = None # for a general installation, we don't need to store the results
CELERY_ACCEPT_CONTENT = ['pickle', ]  # Values are 'pickle', 'json', 'msgpack' and 'yaml'
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"
CELERY_TIMEZONE = 'Europe/Madrid'
CELERY_TASK_DEFAULT_QUEUE = 'tasks'
CELERY_QUEUES = (
    Queue('tasks', routing_key='task.#'),
    Queue('transient', routing_key='transient.#', delivery_mode=1)
)
CELERY_TASK_DEFAULT_EXCHANGE = 'tasks'
CELERY_TASK_DEFAULT_EXCHANGE_TYPE = 'topic'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'task.default'
#########################################
## CONTRIBS
#########################################
INSTALLED_APPS += [
    "taiga_contrib_ldap_auth_ext"
]
ALLOWED_HOSTS = ['*', ]
ENABLE_SLACK: "True"
#########################################
## LDAP CONFIG
#########################################
...... my ldap config....

ENABLE_TELEMETRY = False
PUBLIC_REGISTER_ENABLED = False
``` 
- **nginx proxy vhost configuration**
```
location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_pass http://taiga-gateway:9000/;
  }
```
I have also checked that the ENABLE_SLACK variable is defined in front and back. But when I enter into a project configuration I can't see the slack plugin:

![slack](https://user-images.githubusercontent.com/53336366/126682686-ec0ed3c7-2d5f-4792-9341-3ccfa0967c97.png)

I have also tried to install slack on my own with the slack_contrib_plugin with no results.
Please, could you help me?
