### ISSUE TITLE
[Q] Customisation

### ISSUE THREAD

**Issue by matwong56** [taigaio/taiga-docker#46]
Hello, I am new to Taiga and just tried to implement the Taiga in my server. 

When I tried to customisation. I tried a lot of still but still got 
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.taiga-front: 'PUBLIC_REGISTER_ENABLED'  And my yml file as below

  taiga-front:
    PUBLIC_REGISTER_ENABLED: "True"
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "http://localhost:9000"
      TAIGA_WEBSOCKETS_URL: "ws://localhost:9000"
      TAIGA_SUBPATH: "" # "" or "/subpath"
    networks:
      - taiga

Any idea?
Many thanks!

**Comment by tdelatorre** [comment]
Hi @matwong56 
PUBLIC_REGISTER_ENABLED is an environment variable, move this to environment following the [documentation](https://resources.taiga.io/30min-setup/#customisation).
I hope this helps.

**Comment by matwong56** [comment]
Thank you so much Tdelatorre.
I have added it under taiga-back and taiga-front as per the manual stated.
However, it keep saying that "unsupported cpmfog option for
services.taiga-back" when I try to activate.

I have tried all the customization in the .yml file and all have this
return....

tdelatorre ***@***.***> 於 2021年10月13日 週三 下午8:23寫道：

**Comment by tdelatorre** [comment]
Could you paste the content of your docker-compose.yml please?

**Comment by matwong56** [comment]
Hello, sorry for my late reply

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "http://pms.geligulu.com:9000"
      TAIGA_WEBSOCKETS_URL: "ws://pms.geligulual.com:9000"
      TAIGA_SUBPATH: "" # "" or "/subpath"
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

I capture part of it and not sure if that enough to point out where I
should put the customized code to?

Thanks!
Matthew

tdelatorre ***@***.***> 於 2021年10月13日 週三 下午9:55寫道：

**Comment by tdelatorre** [comment]
At the top of the docker-compose.yml in x-environment you have to put here the default-back-environment variables and in taiga-front service environment the variables for taiga-front.

Something like this:

```
x-environment:
  &default-back-environment
  [your configuration]
  PUBLIC_REGISTER_ENABLED: "True"

taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "xxx"
      TAIGA_WEBSOCKETS_URL: "xxx"
      TAIGA_SUBPATH: "" # "" or "/subpath"
      PUBLIC_REGISTER_ENABLED: "true"
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json
```
In the [requirements](https://resources.taiga.io/30min-setup/#requirements) we explain that it’s necessary to have familiarity with Docker, docker-compose and Docker repositories.

I hope this resolve your problem.

**Comment by ranrinc** [comment]
I got to the point where the domain proxy is working and make some changes on the docker-compose.yml and docker-compose-inits.yml

However when I adding the `PUBLIC_REGISTER_ENABLED: "True"` the main pages becomes blanks and after I put an `#` in front it working again.

And I cant seems to make my AWS SES to work with Taiga, there are no email whatsoever coming even though I'm sure the username/password is correctly setup.

docker-compose.yml
```
version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: blablabla
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "SECRET"
  TAIGA_SITES_SCHEME: "https"
  TAIGA_SITES_DOMAIN: "bugs.mydomain.com"
  TAIGA_SUBPATH: "" # "" or "/subpath"
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "no-reply@mydomain.com"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "True"
  EMAIL_HOST: "email-smtp.amazonaws.com"
  EMAIL_PORT: 587
  EMAIL_HOST_USER: "user"
  EMAIL_HOST_PASSWORD: "blablabla"
  # Rabbitmq settings
  # Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: blablabla
  # Telemetry settings
  ENABLE_TELEMETRY: "True"
  #
  PUBLIC_REGISTER_ENABLED: "True"
  #ENABLE_SLACK: "True"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py


services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: blablabla
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: blablabla
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "https://bugs.mydomain.com"
      TAIGA_WEBSOCKETS_URL: "wss://bugs.mydomain.com"
      TAIGA_SUBPATH: "" # "" or "/subpath"
      PUBLIC_REGISTER_ENABLED: "True"
      #ENABLE_SLACK: "True"
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: blablabla
      TAIGA_SECRET_KEY: "SECRET"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: blablabla
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: 360
      SECRET_KEY: "SECRET"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "iplocal:9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
```

and 

docker-compose-inits.yml
```
version: "3.5"

x-environment:
  &default-back-environment
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: blablabla
  POSTGRES_HOST: taiga-db
  TAIGA_SECRET_KEY: "SECRET"
  # these rabbitmq settings should be the same as
  # in taiga-rabbitmq and taiga-events services
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: blablabla
  CELERY_ENABLED: "False"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py

services:
  taiga-manage:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
    volumes: *default-back-volumes
    networks:
      - taiga
```
