### ISSUE TITLE
ADMIM.MEMBERSHIP.ERROR_SEND_INVITATION

### ISSUE THREAD

**Issue by Ramesh0807** [taigaio/taiga-docker#56]
**Email not sent**
i have enable email setting in docker taiga as per our smtp server but when i trying to resend mail for member showing error.

**docker-compose.yml**
```
version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "taiga-back-secret-key"
  TAIGA_SITES_DOMAIN: "1.XX.YY.ZZ:9000"
  TAIGA_SITES_SCHEME: "http"
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "mail id"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "True"
  EMAIL_HOST: "smtp.office365.com"
  EMAIL_PORT: 587
  EMAIL_HOST_USER: "my mail id"
  EMAIL_HOST_PASSWORD: "mypwd"
  # Registration
  PUBLIC_REGISTER_ENABLED: "True"
  # Telemetry settings
  ENABLE_TELEMETRY: "False"
  # Rabbitmq settings
  # should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  # Github settings
  # Get these in your profile https://github.com/settings/apps
  # or in your organization profile https://github.com/organizations/{ORGANIZATION-SLUG}/settings/applications
  GITHUB_API_CLIENT_ID: "github-api-client-id"
  GITHUB_API_CLIENT_SECRET: "github-api-client-secret"
  # Gitlab settings
  # Get these in your profile https://{YOUR-GITLAB}/profile/applications
  # or in your organization profile https://{YOUR-GITLAB}/admin/applications
  GITLAB_API_CLIENT_ID: "gitlab-api-client-id"
  GITLAB_API_CLIENT_SECRET: "gitlab-api-client-secret"
  GITLAB_URL: "gitlab-url"
  # IMPORTERS
  ENABLE_GITHUB_IMPORTER: "False"
  GITHUB_IMPORTER_CLIENT_ID: "client-id-from-github"
  GITHUB_IMPORTER_CLIENT_SECRET: "client-secret-from-github"
  ENABLE_JIRA_IMPORTER: "False"
  JIRA_IMPORTER_CONSUMER_KEY: "consumer-key-from-jira"
  JIRA_IMPORTER_CERT: "cert-from-jira"
  JIRA_IMPORTER_PUB_CERT: "pub-cert-from-jira"
  ENABLE_TRELLO_IMPORTER: "False"
  TRELLO_IMPORTER_API_KEY: "api-key-from-trello"
  TRELLO_IMPORTER_SECRET_KEY: "secret-key-from-trello"


x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py


services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "http://1.XX.YY.ZZ:9000"
      TAIGA_WEBSOCKETS_URL: "ws://1.XX.YY.ZZ:9000"
      PUBLIC_REGISTER_ENABLED: "true"
      # Get these in your profile https://github.com/settings/apps
      # or in your organization profile https://github.com/organizations/{ORGANIZATION-SLUG}/settings/applications
      GITHUB_CLIENT_ID: "github-client-id"
      # Get these in your profile https://{YOUR-GITLAB}/profile/applications
      # or in your organization profile https://{YOUR-GITLAB}/admin/applications
      GITLAB_CLIENT_ID: "gitlab-client-id"
      GITLAB_URL: "gitlab-url"
      # IMPORTERS
      ENABLE_GITHUB_IMPORTER: "false"
      ENABLE_JIRA_IMPORTER: "false"
      ENABLE_TRELLO_IMPORTER: "false"
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "taiga-back-secret-key"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: 360
      SECRET_KEY: "taiga-back-secret-key"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:

networks:
  taiga:


```

**Behavior**
```
+ exec docker-compose -f docker-compose.yml -f docker-compose.penpot.yml up -d
WARNING: The n0rep variable is not set. Defaulting to a blank string.
taiga-docker_penpot-redis_1 is up-to-date
taiga-docker_taiga-async-rabbitmq_1 is up-to-date
taiga-docker_penpot-exporter_1 is up-to-date
taiga-docker_taiga-protected_1 is up-to-date
taiga-docker_taiga-events-rabbitmq_1 is up-to-date
taiga-docker_taiga-front_1 is up-to-date
taiga-docker_penpot-postgres_1 is up-to-date
taiga-docker_taiga-db_1 is up-to-date
taiga-docker_taiga-events_1 is up-to-date
taiga-docker_penpot-backend_1 is up-to-date
Recreating taiga-docker_taiga-back_1 ... 
Recreating taiga-docker_taiga-back_1 ... done
Recreating taiga-docker_taiga-gateway_1 ... done
Recreating taiga-docker_taiga-async_1   ... done
```
**sudo docker-compose ps**
```
                              Name                              Command               State                                     Ports                                   
----------------------------------------------------------------------------------------------------------------------------------------------------------
taiga-docker_taiga-async-rabbitmq_1    docker-entrypoint.sh rabbi ...   Up      15671/tcp, 15672/tcp, 15691/tcp, 15692/tcp, 25672/tcp, 4369/tcp, 5671/tcp,
                                                                                5672/tcp                                                                  
taiga-docker_taiga-async_1             /taiga-back/docker/async_e ...   Up      8000/tcp                                                                  
taiga-docker_taiga-back_1              ./docker/entrypoint.sh           Up      8000/tcp                                                                  
taiga-docker_taiga-db_1                docker-entrypoint.sh postgres    Up      5432/tcp                                                                  
taiga-docker_taiga-events-rabbitmq_1   docker-entrypoint.sh rabbi ...   Up      15671/tcp, 15672/tcp, 15691/tcp, 15692/tcp, 25672/tcp, 4369/tcp, 5671/tcp,
                                                                                5672/tcp                                                                  
taiga-docker_taiga-events_1            ./docker/entrypoint.sh           Up      8888/tcp                                                                  
taiga-docker_taiga-front_1             /docker-entrypoint.sh ngin ...   Up      80/tcp                                                                    
taiga-docker_taiga-gateway_1           /docker-entrypoint.sh ngin ...   Up      0.0.0.0:9000->80/tcp                                                      
taiga-docker_taiga-protected_1         ./docker/entrypoint.sh           Up      8003/tcp 
```
**Versions**
 - Docker version 19.03.8, build afacb8b7f0
 - docker-compose version 1.25.0, build unknown

email not send from taiga server? is there any configuration is wrong?
