### ISSUE TITLE
An nginx conf file example for a public domain..

### ISSUE THREAD

**Issue by dpineiden** [taigaio/taiga-docker#58]
Hi. 

I've spend some days trying to configure well the system.

Until now i can go to the main interface ok.

But:

- can't open 'admin' and the 'event's like register a new user nothing happend.

I'm sure my nginx file must be fixed but I don't kwon how. Could you put an example for this case (a public domain, no local)

Here my file

```
# Taiga project managment
server {
       server_name proyectos.tecnocomunes.org;
       
	listen 80;
	listen [::]:80;

    if ($host = proyectos.tecnocomunes.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

}



server {
       listen 443 ssl http2;
       server_name proyectos.tecnocomunes.org proyectos.tecnocomunes.cl;


    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    access_log /var/log/nginx/access_proyectos.log;
    error_log /var/log/nginx/error_proyectos.log;

       ### Certificado ssl
    ssl_certificate /etc/letsencrypt/live/tecnocomunes.org/fullchain.pem; # 
    ssl_certificate_key /etc/letsencrypt/live/tecnocomunes.org/privkey.pem; # 
    ssl_dhparam /etc/ssl/certs/dhparam.pem;

   # [ssl part ommited now]
     # END Certificado SSL

       location / {
	   proxy_set_header Host $http_host;
	   proxy_set_header X-Real-IP $remote_addr;
	   proxy_set_header X-Scheme $scheme;
	   proxy_set_header X-Forwarded-Proto $scheme;
	   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	   proxy_redirect off;
	   proxy_pass http://localhost:9000/;
	 }


       location /admin/ {
	   proxy_set_header Host $http_host;
	   proxy_set_header X-Real-IP $remote_addr;
	   proxy_set_header X-Scheme $scheme;
	   proxy_set_header X-Forwarded-Proto $scheme;
	   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	   proxy_pass http://localhost:9000/admin/;	   
	   proxy_redirect off;
	 }

	 # Events
	 location /events {
	     proxy_pass http://localhost:9000/events;
	     proxy_http_version 1.1;
	     proxy_set_header Upgrade $http_upgrade;
	     proxy_set_header Connection "upgrade";
	     proxy_connect_timeout 7d;
	     proxy_send_timeout 7d;
	     proxy_read_timeout 7d;
	 }


        # Backend
        location /api {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://localhost:9000/api;
            proxy_redirect off;
        }


        # Static files
        location /static/ {
            alias /var/lib/docker/volumes/taiga-docker_taiga-static-data/_data/;
	    
        }
    # Media
    location /_protected {
        internal;
        alias /var/lib/docker/volumes/taiga-docker_taiga-media-data/_data/;
        add_header Content-disposition "attachment";
    }

    # Unprotected section
    location /media/exports {
        alias /var/lib/docker/volumes/taiga-docker_taiga-media-data/_data/exports;
        add_header Content-disposition "attachment";
    }

        # Media files
        location /media {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:9000/;	
        proxy_redirect off;	
        }

}
```

/admin -> error 502
/events -> no events

The docker-compose file:

```
version: "3.5"

x-environment:
  &default-back-environment
# Database settings
  - POSTGRES_DB=taiga
  - POSTGRES_USER=taiga
  - POSTGRES_PASSWORD=taiga
  - POSTGRES_HOST=taiga-db
  # Taiga settings
  - TAIGA_SECRET_KEY="O7SKD0BNPMQmZ2pWznL0MpxhQFzafDi9uAsyLeck9vBSCdEMZcj0fwZhKHQmk5Tb"
  - SECRET_KEY="O7SKD0BNPMQmZ2pWznL0MpxhQFzafDi9uAsyLeck9vBSCdEMZcj0fwZhKHQmk5Tb"  
  - TAIGA_SITES_DOMAIN="www.tecnocomunes.org"
  - TAIGA_SITES_SCHEME="https"
  # Email settings. Uncomment following lines and configure your SMTP server
  # Rabbitmq settings
  # Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  - RABBITMQ_USER=taiga
  - RABBITMQ_PASS=taiga
  # Telemetry settings
  - ENABLE_TELEMETRY="True"
  - SESSION_COOKIE_SECURE="True"
  - CSRF_COOKIE_SECURE="True"
  - FEEDBAKC_ENABLE="True"
  - FEEDBACK_EMAIL="email@tecnocomunes.org"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  - taiga-config-data:/taiga-back/settings


services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment:
      - TAIGA_SECRET_KEY="O7SKD0BNPMQmZ2pWznL0MpxhQFzafDi9uAsyLeck9vBSCdEMZcj0fwZhKHQmk5Tb"
      - EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
      - DEFAULT_FROM_EMAIL="email@tecnocomunes.org"
      - EMAIL_USE_TLS="True"
      - EMAIL_USE_SSL="False"
      - EMAIL_HOST="email.domain.org"
      - EMAIL_PORT=587
      - EMAIL_HOST_USER="mail@domain.org"
      - EMAIL_HOST_PASSWORD="<zx<zx<zx<zx
      - SESSION_COOKIE_SECURE="True"
      - CSRF_COOKIE_SECURE="True"
      - FEEDBAKC_ENABLE="True"
      - FEEDBACK_EMAIL="mail@domain.org"      
    env_file:
     - ./variables.env
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "https://proyectos.tecnocomunes.org"
      TAIGA_WEBSOCKETS_URL: "wss://proyectos.tecnocomunes.org"
      PUBLIC_REGISTER_ENABLED: "true"
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "asdasdasdaszxcas"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: 360
      SECRET_KEY: "asdasdasdaszxcas"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-config-data:
  taiga-db-data:

networks:
  taiga:

```
Thanks!

**Comment by sxenny** [comment]
as I understood you should change TAIGA_SITES_DOMAIN="www.tecnocomunes.org" to TAIGA_SITES_DOMAIN="proyectos.tecnocomunes.org"

and in your Nginx must contain those locations inside server listen 443

```

      server_name proyectos.tecnocomunes.org

location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_pass http://localhost:9000/;
  }

  # Events
  location /events {
      proxy_pass http://localhost:9000/events;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_connect_timeout 7d;
      proxy_send_timeout 7d;
      proxy_read_timeout 7d;
  }
```


so it looks like your external Nginx just proxying taiga dockers...

It work for me BUT I have there is a strange moment with events too. it's WebSocket connection error in console log
If I do a fresh install or delete all containers, images volumes and try to fresh install then everything works fine. 

I can create superuser by CLI, next I can create a new project and wait some minutes to confirm that WebSockets error don't appear in console (F12 browser)
But if I type docker-compose Down and start it back by docker-compose up -d I can see  WebSockets error immediately 

Can you confirm the same?

**Comment by dpineiden** [comment]
Hi.
Is a fresh install, I've tried twice. The only thing that I modify on the docker folder are:
- email variables
- hosting variables

Is not very clear how to map the:
- events
- admin
- statics 

to the taiga dockers. 

If you see, there a group of many container:

- taiga-front :: is in angular.js i guess, and must answer to websockets with 'event's
- taiga-backend :: must answer to the 'admin' pages.

In the server, inside, I get answer using curl to the admin page.

How do you test websocket in CLI? what command?

So on...

**Comment by sxenny** [comment]
> Hi.
> Is a fresh install, I've tried twice. The only thing that I modify on the docker folder are:
> 
> * email variables
> * hosting variables
> 
> Is not very clear how to map the:
> 
> * events
> * admin
> * statics
> 
> to the taiga dockers.
> 
> If you see, there a group of many container:
> 
> * taiga-front :: is in angular.js i guess, and must answer to websockets with 'event's
> * taiga-backend :: must answer to the 'admin' pages.
> 
> In the server, inside, I get answer using curl to the admin page.
> 
> How do you test websocket in CLI? what command?
> 
> So on...

I tested via Web interface. When I opened taiga.mydomain.com/admin/  (here was no css styles, but I fixed it by cancel my modified docker-compose.yml volume's path for static )
I also tested WebSocket via Web interface. First start `docker-compose up -d` I create superuser next I login and create a new project, then type `docker-compose down` and start it again `docker-compose up -d`. Go to web interface, login, open project and wait 1-2 minutes I can see to many WebSocker errors in Google Chrome WebTools F12 in Console tab

**Comment by dpineiden** [comment]
Hi.

First, i had the same problem with static folder, how do you fix that?

I had the websockets errors on events.

....

**Comment by sxenny** [comment]
IF you already create superuser by 
` ./taiga-manage.sh createsuperuser`

than try to do this 
 `./taiga-manage.sh collectstatics`

My /admin/ locate was broken css style when I modified my docker-compose.yml. I a little change this:
```
x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  - taiga-config-data:/taiga-back/settings
```

tho this 

```
x-volumes:
  &default-back-volumes
  - ./taiga-static-data:/taiga-back/static
  - ./taiga-media-data:/taiga-back/media
  - ./taiga-config-data:/taiga-back/settings
```

ant this movie force to broken css style, when I go changes back it working well

BTW my External Nginx conf not look like you it's look here:

location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_pass http://localhost:9000/;
  }

  # Events
  location /events {
      proxy_pass http://localhost:9000/events;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_connect_timeout 7d;
      proxy_send_timeout 7d;
      proxy_read_timeout 7d;
  }

**Comment by wereii** [comment]
I am experiencing the same problems, after a bit of debugging thru `docker container logs <id>` I found that even the gataway image itself is giving errors on `/admin` or `/events` access, either bad gateway or connection refused.

For my case I found that taiga-events hangs on the [recursive chown in entrypoint.sh](https://github.com/taigaio/taiga-events/blob/b11f7693032af74b2b156b1f1581d32ba4229e55/docker/entrypoint.sh#L27) which is probably caused by my [VPS providers kernel/overlay2 setup?](https://github.com/taigaio/taiga-events/blob/b11f7693032af74b2b156b1f1581d32ba4229e55/docker/entrypoint.sh#L27)

I will move the same config of mine to bare hardware and see if it works ootb.

**Comment by sxenny** [comment]
> I am experiencing the same problems.
> After a bit of debugging thru `docker container logs <id>` I found that even the gataway image itself is giving errors on `/admin` or `/events` access, either bad gateway or connection refused.
> 
> For my case I found that taiga-events hangs on the [recursive chown in entrypoint.sh](https://github.com/taigaio/taiga-events/blob/b11f7693032af74b2b156b1f1581d32ba4229e55/docker/entrypoint.sh#L27) which is probably caused by my [VPS providers kernel/overlay2 setup?](https://github.com/taigaio/taiga-events/blob/b11f7693032af74b2b156b1f1581d32ba4229e55/docker/entrypoint.sh#L27)
> 
> I will move the same config of mine to bare hardware and see if it works ootb.

did you find a solution out?

**Comment by dpineiden** [comment]
Now, I think I solve some of those problems:

1) Statics for admin url.

First on the 'docker-compose.yml' file starts the volumes with './'
Then, on the host give the permissions to www-data (the web user for nginx)

Test from your computer that:

```
curl  https://www.domain.org/static/admin/css/base.css 
```
If returns the  css file all is ok, Otherwise try yo change the permissions on the volumes path.


```
chmod 766 -R /var/lib/docker/volumes/taiga-docker_taiga-static-data/_data/
chmod 766 -R /var/lib/docker/volumes/taiga-docker_taiga-media-data/_data/
chown :www-data -R /var/lib/docker/volumes/taiga-docker_taiga-static-data/
chown :www-data -R /var/lib/docker/volumes/taiga-docker_taiga-media-data/
```

Maybe you could reduce the level of permissions, try it.

2) For the email sending.

Despite if is working with test sendmail, the variables must be declared at the sstart of the file, not only on the 'inits'

```
x-environment: 
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "asdasdasdasd"
  SECRET_KEY: "asdsadasdsad"  
  TAIGA_SITES_DOMAIN: "www.domain.org"
  TAIGA_SITES_SCHEME: "https"  
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "email@domain.org"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: "smtp.domain.org"
  EMAIL_PORT: 587
  EMAIL_HOST_USER: "email@domain.org"
  EMAIL_HOST_PASSWORD: "<PW>"  
  # Email settings. Uncomment following lines and configure your SMTP server
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  # Telemetry settings
  ENABLE_TELEMETRY: "True"
  PUBLIC_REGISTER_ENABLED: "True"
```
