### ISSUE TITLE
websocket not working over ssl

### ISSUE THREAD

**Issue by alternatiph** [taigaio/taiga-docker#65]
**Describe the bug**
WebSocket does not connect when the 

**To Reproduce**
1. Follow the instruction
2. Use certbot to generate ssl cert
3. ws not working

**Expected behavior**
Browser should be able to connect to WebSocket

**Comment by burtsevyg** [comment]
Try this:
```
...
  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "https://<hostname>"
      TAIGA_WEBSOCKETS_URL: "wss://<hostname>"
...
```

**Comment by alternatiph** [comment]
This does not solve the issue. I have found the problem and have created a pr for that.

**Comment by burtsevyg** [comment]
Did you try wss protocol? Please see my example.

**Comment by alternatiph** [comment]
Of course. That was the first thing I tried too.
There is a problem with the nginx config.
Please see my pull request.

**Comment by burtsevyg** [comment]
It works without changes for me.

**Comment by burtsevyg** [comment]
But in docker-compose I add:
```
  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "https://<hostname>"
      TAIGA_WEBSOCKETS_URL: "wss://<hostname>"
```
