### ISSUE TITLE
Slack integration does not work

### ISSUE THREAD

**Issue by dcubero** [taigaio/taiga-docker#67]
Slack integration does not work after adding the two needed variables to the docker-compose file.
Slack appears under "Plugins" but as soon as I click on Slack the "Oops, something went wrong..." message show up.

**To Reproduce**
1. Configure both variables, one on taiga-front and the other one on taiga-back
2. Recreate the containers
3. Navigate to project’s configuration.
4. Click on PLUGINS
5. See the error

**Expected behavior**
Warning does not show and let configure slack 

**Configuration**
Taiga is behind Nginx reverse proxy

**Versions**
 - docker: Docker version 20.10.5
 - docker-compose: docker-compose version 1.28.2

**Comment by yamila-moreno** [comment]
Hi @dcubero,

can you share the configuration you used in docker-compose.yml for slack? (**with credentials redacted**)

**Comment by dcubero** [comment]
Yes, of course.


```
version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: xxxxxx
  POSTGRES_USER: xxxxxxx
  POSTGRES_PASSWORD: xxxxx
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "xxxxxxx"
  TAIGA_SITES_DOMAIN: "taiga.xxxxxx.com"
  TAIGA_SITES_SCHEME: "https"
  TAIGA_ENABLE_SLACK: "True"
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "xxxxx"
  EMAIL_USE_TLS: "False"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: "xxxxx"
  EMAIL_PORT: 0
  EMAIL_HOST_USER: "xxxxxxxxx"
  EMAIL_HOST_PASSWORD: "xxxxxxx"
  # Registration
  PUBLIC_REGISTER_ENABLED: "False"
  # Telemetry settings
  ENABLE_TELEMETRY: "False"
  # Rabbitmq settings
  # should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: xxxxxxxxx
  RABBITMQ_PASS: xxxxxxxxx

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py:ro

services:
  taiga-db:
    image: postgres:12
    container_name: taiga-db
    restart: always
    hostname: taiga-db
    environment:
      POSTGRES_DB: xxxxxxxx
      POSTGRES_USER: xxxxxxx
      POSTGRES_PASSWORD: xxxxxxx
    volumes:
      - taiga-db:/var/lib/postgresql/data
    networks:
      - taigaNetwork

  taiga-back:
    image: taigaio/taiga-back:latest
    container_name: taiga-back
    restart: always
    hostname: taiga-back
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taigaNetwork
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    container_name: taiga-async
    restart: always
    hostname: taiga-async
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taigaNetwork
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: taiga-rabbitmq
    restart: always
    hostname: taiga-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: xxxxx
      RABBITMQ_DEFAULT_USER: xxxxxxxx
      RABBITMQ_DEFAULT_PASS: xxxxxxx
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taigaNetwork

  taiga-front:
    image: taigaio/taiga-front:latest
    container_name: taiga-front
    restart: always
    hostname: taiga-front
    environment:
      TAIGA_URL: "https://taiga.xxxxx.com"
      TAIGA_WEBSOCKETS_URL: "wss:///taiga.xxxxx.com"
      PUBLIC_REGISTER_ENABLED: "false"
      ENABLE_SLACK: "true"
      ENABLE_GITHUB_IMPORTER: "false"
      ENABLE_JIRA_IMPORTER: "false"
      ENABLE_TRELLO_IMPORTER: "false"
    networks:
      - taigaNetwork
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json:ro

  taiga-events:
    image: taigaio/taiga-events:latest
    container_name: taiga-events
    restart: always
    hostname: taiga-events
    environment:
      RABBITMQ_USER: xxxxxxxxx
      RABBITMQ_PASS: xxxxxxxxx
      TAIGA_SECRET_KEY: "xxxxxxxx"
    networks:
      - taigaNetwork
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: taiga-events-rabbitmq
    restart: always
    hostname: taiga-events-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: xxxx
      RABBITMQ_DEFAULT_USER: xxxxxxxx
      RABBITMQ_DEFAULT_PASS: xxxxxxxx
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taigaNetwork

  taiga-protected:
    image: taigaio/taiga-protected:latest
    container_name: taiga-protec
    restart: always
    hostname: taiga-protec
    environment:
      MAX_AGE: 360
      SECRET_KEY: "xxxxxxxxxx"
    networks:
      - taigaNetwork

  taiga-gateway:
    image: nginx:alpine
    container_name: taiga-gateway
    restart: always
    hostname: taiga-gateway
    ports:
      - "xx:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taigaNetwork
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
    name: taiga-static-data
  taiga-media-data:
    name: taiga-media-data
  taiga-db:
    name: taiga-db

networks:
    taigaNetwork:
        driver: bridge
        name: taigaNetwork
        ipam:
            driver: default
            config:
                - subnet: 'xx.xx.xx.xx'
                  gateway: 'xx.xx.xx.xx'
```
