### ISSUE TITLE
invalid conf.json

### ISSUE THREAD

**Issue by jeffery9** [taigaio/taiga-docker#68]
**Describe the bug**

**To Reproduce**
run taiga in docker
set the URLs in docker-compose.yml
launch-tagai

browse taiga, report `Your conf.json file is not a valid json file, please review it. in console, and report 'GET http://localhost:8000/api/v1/stats/discover net::ERR_CONNECTION_REFUSED'

**Expected behavior**

**Configuration**
If applicable, describe the custom configuration that may affect.
  

docker make a conf.json, and the content is 
/usr/share/nginx/html # cat conf.json
{
    "api": "http://kanban.geninit.cn/api/v1/",
    "eventsUrl": "ws://kanban.geninit.cn/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": false,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "defaultLoginEnabled": true,
    "publicRegisterEnabled": false,
    "feedbackEnabled": true,
    "supportUrl": "https://resources.taiga.io",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "gitHubClientId": "",
    "gitLabClientId": "",
    "gitLabUrl": "",
    "tagManager": { "accountId": null },
    "tribeHost": null,
    "enableAsanaImporter": false,
    "enableGithubImporter": false,
    "enableJiraImporter": false,
    "enableTrelloImporter": false,
    "gravatar": false,
    "rtlLanguages": ["fa"]
}

**Versions**
 - docker
 - docker-compose

**Additional context**

**Comment by yamila-moreno** [comment]
Hi @jeffery9, in order to help you, we need more information:

- if you go to `http://localhost:9000/conf.json` can you see the file?
- share your `docker-compose.yml`(**with the credentials redacted**)
- is it anything in docker-compose logs?

**Comment by zhoukuo** [comment]
repro too,
when go to http://localhost:9000/conf.json, I can see the file
the docker logs show : "GET /conf.json HTTP/1.0" 304

**Comment by zhoukuo** [comment]
repro too,
when go to http://localhost:9000/conf.json, I can see the file
the docker logs show : "GET /conf.json HTTP/1.0" 304

**Comment by jeffery9** [comment]
have fixed this by setup  ENV in docker-compose yaml files, like this.
```
  ENABLE_GITHUB_IMPORTER : "True"
  ENABLE_JIRA_IMPORTER: "True"
  ENABLE_TRELLO_IMPORTER: "True"
  
```
this should let docker-compose re-generate conf.json.

there have another solution is to customize `conf.json`  via volume
```
  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "http://localhost:9000"
      TAIGA_WEBSOCKETS_URL: "ws://localhost:9000"
    networks:
      - taiga
    volumes:
      - ./conf.json:/usr/share/nginx/html/conf.json
```

the content of `conf.json` should like this one 
```
{
    "api": "http://kanban.geninit.cn/api/v1/",   ========== refer to your url
    "eventsUrl": "ws://kanban.geninit.cn/events",    =================refer to your ws url
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": false,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "defaultLoginEnabled": true,
    "publicRegisterEnabled": false,
    "feedbackEnabled": true,
    "supportUrl": "https://resources.taiga.io",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "gitHubClientId": "",
    "gitLabClientId": "",
    "gitLabUrl": "",
    "tagManager": { "accountId": null },
    "tribeHost": null,
    "enableAsanaImporter": false,
    "enableGithubImporter": false,
    "enableJiraImporter": false,
    "enableTrelloImporter": false,
    "gravatar": true,
    "rtlLanguages": ["fa"]
}

```

**Comment by zhoukuo** [comment]
as your design, the boolean value is "False" in the docker-compose.yml, and convert to "false" in the conf.json, but it does not convert correctly. it still "False" in conf.json.
for example, I want to enable public register, so I set PUBLIC_REGISTER_ENABLED: "True" in docker-compose.yml, it should be  "publicRegisterEnabled": true, but actually it is "publicRegisterEnabled": True.

**Comment by yamila-moreno** [comment]
@jeffery9 I'm trying to reproduce the error but I cannot, can you explain step by step all the actions you did?

As a general information, there are two ways of configuration:
1. simple. With environment variables in docker-compose.yml 
2. advanced. Mapping a `conf.json` with all the configuration. The api url should be edited as well; if it says `localhost:8000` is not correct.

@zhoukuo it's not super clear that you have the same problem. I suggest you open a new issue detailing you problem so we can help. Provide configuration and all the steps.

Cheers!

**Comment by jeffery9** [comment]
my docker-compose.yaml , good lucks


```
version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "taiga-back-secret-key"
  TAIGA_SITES_DOMAIN: "kanban.geninit.cn"
  TAIGA_SITES_SCHEME: "http"
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "no-reply@geninit.cn"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "True"
  EMAIL_HOST: "smtp.exmail.qq.com"
  EMAIL_PORT: 465
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
  # Rabbitmq settings
  # Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  # Telemetry settings
  ENABLE_TELEMETRY: "True"
  PUBLIC_REGISTER_ENABLED: "True"
  ENABLE_GITHUB_IMPORTER: "False" 
  ENABLE_JIRA_IMPORTER: "False" 
  ENABLE_TRELLO_IMPORTER: "False" 


x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config/config.py:/taiga-back/settings/config.py


services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "http://kanban.geninit.cn"
      TAIGA_WEBSOCKETS_URL: "ws://kanban.geninit.cn"
    networks:
      - taiga
    # volumes:
      # - ./config/conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "taiga-back-secret-key"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: 360
      SECRET_KEY: "taiga-back-secret-key"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:

networks:
  taiga:
```
