### ISSUE TITLE
Help: Traefik on top of taiga-gateway

### ISSUE THREAD

**Issue by xcojonny** [taigaio/taiga-docker#71]
Hello together,

first of all thanks for the image! Its working wonderful if I'm using it without any proxy and just accessing it from http://IP:9000.

Hopefully I'm not messing anything up...
For my home-server project I'm using traefik, so i would like to use it also for this image. But unfortunately I'm struggeling a bit with this. I've added the traefik labels to the gateway (these labels function for all my other containers). 

```yml
taiga-gateway: 
...
    networks:
        - taiga
        - proxy
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.taiga-secure.entrypoints=https"
        - "traefik.http.routers.taiga-secure.rule=Host(`${HOST}`)" 
        - "traefik.http.routers.taiga-secure.tls=true"
        - "traefik.http.routers.taiga-secure.service=taiga"
        - "traefik.http.services.taiga.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.taiga-secure.middlewares=secHeaders@file"
```
traefik-yml for sec header:

```yml
...
http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
```

Weird thing is, that i can access the admin page with no problems.  When i try to open the HOST (frontend) I'll get blank page and firefox is telling me in the console:
```log
Uncaught DOMException: The operation is insecure.
```
and 
```log
GEThttps://HOST/...
[HTTP/2 502 Bad Gateway 0ms]	
GET
	https://HOST/...
Status502
Bad Gateway
VersionHTTP/2
Übertragen11 B (11 B Größe)
Referrer Policystrict-origin-when-cross-origin
```

Does any body out there have any clou? Anything that could help is welcome :)

Thanks in advance!!

**Comment by saul-avikar** [comment]
Not too sure if this is part of your problem or not because I am not familiar with your setup but I was getting the `Uncaught DOMException: The operation is insecure.` problem as well when I had the `TAIGA_WEBSOCKETS_URL` set to use **ws://** instead of **wss://** which broke it when everything else was setup for https.

**Comment by xcojonny** [comment]
wow, thanks a lot!
You've saved my day!

This is the problem...

**Comment by Zen3515** [comment]
I'm trying to self host taiga with traefik in front but I couldn't make this work.
I'm stuck with unable to login `admin` `123123` with error 401 telling me that it's unable to authenticate me.
```
Oops, something went wrong...
According to the Taiga, your username/email or password are incorrect.
```
Could you please share your full configuration?

here's mine currently.
```yaml
version: "3.5"

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - /data/services-data/taiga/taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga-network
    deploy:
      placement:
        constraints:
          - node.hostname==my-server

  taiga-back:
    image: taigaio/taiga-back:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY}"
      TAIGA_SITES_SCHEME: "${TAIGA_SITES_SCHEME}"
      TAIGA_SITES_DOMAIN: "${TAIGA_SITES_DOMAIN}"
      TAIGA_SUBPATH: "${TAIGA_SUBPATH}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      ENABLE_TELEMETRY: "${ENABLE_TELEMETRY}"
    volumes: 
      - /data/services-data/taiga/taiga-static-data:/taiga-back/static
      - /data/services-data/taiga/taiga-media-data:/taiga-back/media
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq
    networks:
      - taiga-network
    deploy:
      placement:
        constraints:
          - node.hostname==my-server

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY}"
      TAIGA_SITES_SCHEME: "${TAIGA_SITES_SCHEME}"
      TAIGA_SITES_DOMAIN: "${TAIGA_SITES_DOMAIN}"
      TAIGA_SUBPATH: "${TAIGA_SUBPATH}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      ENABLE_TELEMETRY: "${ENABLE_TELEMETRY}"
    volumes: 
      - /data/services-data/taiga/taiga-static-data:/taiga-back/static
      - /data/services-data/taiga/taiga-media-data:/taiga-back/media
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq
    networks:
      - taiga-network
    deploy:
      placement:
        constraints:
          - node.hostname==my-server

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
    volumes:
      - /data/services-data/taiga/taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga-network
    deploy:
      placement:
        constraints:
          - node.hostname==my-server

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "${TAIGA_URL}"
      TAIGA_WEBSOCKETS_URL: "${TAIGA_WEBSOCKETS_URL}"
      TAIGA_SUBPATH: "${TAIGA_SUBPATH}"
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json
    networks:
      - taiga-network
    deploy:
      placement:
        constraints:
          - node.hostname==my-server

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY}"
    depends_on:
      - taiga-events-rabbitmq
    networks:
      - taiga-network
    deploy:
      placement:
        constraints:
          - node.hostname==my-server

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
    volumes:
      - /data/services-data/taiga/taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga-network
    deploy:
      placement:
        constraints:
          - node.hostname==my-server

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "${MAX_AGE}"
      SECRET_KEY: "${SECRET_KEY}"
    networks:
      - taiga-network
    deploy:
      placement:
        constraints:
          - node.hostname==my-server

  taiga-gateway:
    image: nginx:1.19-alpine
    # ports:
    #   - "9000:80"
    volumes:
      - /data/services-data/taiga/taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - /data/services-data/taiga/taiga-static-data:/taiga/static
      - /data/services-data/taiga/taiga-media-data:/taiga/media
    networks:
      - taiga-network
      - traefik-public
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
    deploy:
      placement:
        constraints:
          - node.hostname==my-server
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.taiga-http.rule=Host(`${TAIGA_SITES_DOMAIN?Variable not set}`)
        - traefik.http.routers.taiga-http.entrypoints=http
        - traefik.http.routers.taiga-http.middlewares=https-redirect
        - traefik.http.routers.taiga-https.rule=Host(`${TAIGA_SITES_DOMAIN?Variable not set}`)
        - traefik.http.routers.taiga-https.entrypoints=https
        - traefik.http.routers.taiga-https.tls=true
        - traefik.http.routers.taiga-https.tls.certresolver=le
        - traefik.http.services.taiga.loadbalancer.server.port=80

networks:
  taiga-network:
    attachable: true
  traefik-public:
    external: true
```

with the following environment variables
```shell
# https://github.com/kaleidos-ventures/taiga-docker
# Database settings
export POSTGRES_DB=taiga
export POSTGRES_USER=taiga
export POSTGRES_PASSWORD='retracted-1'
export POSTGRES_HOST=taiga-db
# Taiga settings
export TAIGA_SECRET_KEY="retracted-2"
export TAIGA_SITES_SCHEME="https"
export TAIGA_SITES_DOMAIN="taiga.example.com"
export TAIGA_SUBPATH="" # "" or "/subpath"
# Rabbitmq settings
# Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
export RABBITMQ_USER=taiga
export RABBITMQ_PASS='retracted-3'
# Telemetry settings
export ENABLE_TELEMETRY="True"
# taiga-async-rabbitmq
export RABBITMQ_ERLANG_COOKIE=secret-erlang-cookie
export RABBITMQ_DEFAULT_USER=taiga
export RABBITMQ_DEFAULT_PASS='retracted-3'
export RABBITMQ_DEFAULT_VHOST=taiga
# taiga-front
export TAIGA_URL="https://taiga.example.com"
export TAIGA_WEBSOCKETS_URL="wss://taiga.example.com"
export TAIGA_SUBPATH="" # "" or "/subpath"
# taiga-protected
export MAX_AGE=360
export SECRET_KEY="retracted-2"
```
